### ISSUE TITLE
pins_arduino.h

### ISSUE THREAD

**Issue by nikthefix** [UnexpectedMaker/tinys2#2]
Hello, 
Forgive me if I've misunderstood this but it appears that the tinyS2 variant default pin assignments for FSPI bus do not tally with the printed pinout sheet or with the pins file for the standard esp32-s2 in boards manager. The result (for me) is that on the tinyS2, SPI TFT displays fail to initialize after a soft reset - no problem if the board is power cycled. Modifying tinyS2 pins_arduino.h fixes this for me. Love the board BTW. I'm working on some accessories for it.

**Comment by UnexpectedMaker** [comment]
Sorry, I don't understand. `pins_arduino.h` for the TinyS2 in 2.0.0 of the Arduino Core matches the printed pinout sheet and the sheet online on my website. Please show me were they don't match?

```static const uint8_t SS    = 14;
static const uint8_t MOSI  = 35;
static const uint8_t MISO  = 36;
static const uint8_t SDO  = 35;
static const uint8_t SDI  = 36;
static const uint8_t SCK   = 37;
```
With regards to them matching other S2 boards, they don't need to. SPI like most other peripherals on the ESP can use any pins for FSPI as they all go through the internal IO Mux anyway. 

I have no initialisation issues with my 320x240 TFT on my Reflow Master Pro after a soft reset here running on one of my S2 boards using the exact same IO as the TinyS2. Maybe you have not wired the reset pin on the screen correctly?

**Comment by nikthefix** [comment]
[image: TinyS2_V1_pinout_card.jpg]
Aha! So I accidentally downloaded this out of date pinout card. Pilot
error. Thanks for the quick response.

**Comment by UnexpectedMaker** [comment]
> [image: TinyS2_V1_pinout_card.jpg] Aha! So I accidentally downloaded this out of date pinout card. Pilot error. Thanks for the quick response.
> […](#)

From where? There should be no out of date pinout diagrams anywhere online.

**Comment by nikthefix** [comment]
I'll try to find it again. I downloaded it a long time ago (before I
purchased the board) from what I thought was your website (could it have
preliminary info?). I should have checked it against the card that came
with the product - which of course is correct. Sorry about that. If I find
the bad card anywhere else I'll send you a link.
